apiVersion: v1
kind: Pod
metadata:
  name: anomalizer-ui
spec:
  containers:
  - name: anomalizer-ui
    image: ghcr.io/pogadog/anomalizer-ui:latest
    ports:
    - containerPort: 3001
    env:
    - name: PORT
      value: "3001"
  imagePullSecrets:
  - name: regcred
  